apiVersion: v1
kind: ConfigMap
metadata:
  name: mk2-config
data:
  CORS_ORIGIN: "https://www.jsh-ai-dev.com"
  NOTES_SERVICE_URL: "http://mk1-app.pos-mk1.svc.cluster.local:8080"
  MK3_SCRAPER_REFRESH_ENABLED: "false"
