apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pos-mk2

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/auth.yaml
  - ../../base/api.yaml
  - ../../base/web.yaml
  - ../../base/ingress.yaml
  - secret.aws.yaml
  - issuer.letsencrypt.yaml
  - certificate.mk2.yaml

patches:
  - path: configmap.aws.patch.yaml
  - path: ingress.aws.patch.yaml

images:
  - name: personal-operating-system-mk2-web
    newName: 948360715051.dkr.ecr.ap-northeast-2.amazonaws.com/personal-operating-system-mk2-web
    newTag: latest
  - name: personal-operating-system-mk2-api
    newName: 948360715051.dkr.ecr.ap-northeast-2.amazonaws.com/personal-operating-system-mk2-api
    newTag: latest
  - name: personal-operating-system-mk2-auth
    newName: 948360715051.dkr.ecr.ap-northeast-2.amazonaws.com/personal-operating-system-mk2-auth
    newTag: latest
